FROM oven/bun:1-alpine

WORKDIR /app

ARG DATABASE_URL

COPY . .

RUN  bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD [ "bun" , "run" , "start:web"]