name: Deploying the Websocket
on:
  push:
    branches: ['main']

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build the image and push it to dockerhub      
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: ./docker/dockerfile.ws
          push: true
          tags: sayan14/web-socket:${{github.sha}}